"""Self-serve SaaS product configuration."""

from __future__ import annotations

from config.default_config import AppConfig, BrandingConfig, ReportBrandingConfig
from engine.schemas import GradeReportConfig


SAAS_CONFIG = AppConfig(
    mode="saas",
    branding=BrandingConfig(
        app_name="Student Grade Report Cleaner",
        page_title="Student Grade Report Cleaner",
        show_branding=False,
        primary_color="#2563eb",
        accent_color="#1d4ed8",
    ),
    report_branding=ReportBrandingConfig(
        report_title="Student Progress Report",
        header_text="Student progress report for parent or teacher review",
        footer_text="Generated by Student Grade Report Cleaner.",
    ),
    grade_report=GradeReportConfig(),
)
